name: Detect Yarn mode

description: Detect whether the repository is using Yarn Berry (modern) or Yarn Classic.

outputs:
  berry:
    description: "true when Yarn Berry is detected; otherwise false"
    value: ${{ steps.detect.outputs.berry }}

runs:
  using: composite
  steps:
    - id: detect
      shell: bash
      run: |
        set -euo pipefail

        berry=false

        if [[ -f .yarnrc.yml || -d .yarn ]]; then
          berry=true
        fi

        # package.json may declare a Yarn version via the `packageManager` field.
        # When present, the optional helper script refines detection using that field.
        # It should exit with status 0 when Yarn Berry is detected, and non-zero otherwise.
        if [[ -f .github/scripts/is-yarn-berry.js ]]; then
          if node .github/scripts/is-yarn-berry.js; then
            berry=true
          fi
        else
          echo "::notice title=Using heuristic Yarn detection::.github/scripts/is-yarn-berry.js not found; using heuristic detection."
          echo "Heuristic detection is based on the presence of .yarnrc.yml or the .yarn directory."
          echo "For packageManager-based detection, add .github/scripts/is-yarn-berry.js that exits 0 when Yarn Berry is detected and non-zero otherwise."
        fi

        echo "berry=$berry" >> "$GITHUB_OUTPUT"
